---
# tasks file for dev
- name: install docker prerequisities
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
  become: yes

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes


- name: Add docker repo
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  become: yes

- name: Install dev packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - git
    update_cache: yes
  become: yes

- name: Add docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add current user to group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  become: yes
