---
- name: First playbook
  hosts:
    - webservers

  vars:
    servers: 
      - galaxy
      - vulcan
      - ameros
    bg_img_dest: /home/vagrant/Pictures/bg.jpg


  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes
      become: yes
      tags:
        - packages

    - name: Add php8.0 repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      become: yes
      tags:
        - packages 

    # apt-get install htop vim php8.0 kazam filezilla bluefish
    - name: Install base packages
      apt:
        name:
          - htop
          - vim
          - php8.0
          - kazam
          - filezilla
          - bluefish
        state: present
        update_cache: yes
      become: yes
      tags:
        - packages

    - name: Download bg image
      get_url:
        url: https://cdn.wallpapersafari.com/55/73/ghY4rc.jpg
        dest: "{{ bg_img_dest }}"
      tags:
        - background

    - name: Set bg image
      shell: "gsettings set org.gnome.desktop.background picture-uri 'file://{{ bg_img_dest }}'"
      tags:
        - background

    - name: Create files from template {{ ansible_hostname }}
      template:
        src: template.j2
        dest: "/tmp/{{ item }}.txt"
      loop: "{{ servers }}"
      tags:
        - template

  # # handlers:
  # #   - name: start mysql service
  # #     service: 
  # #       name: mysqld
  # #       state: started
  # #     become: yes