---
- name: First playbook
  hosts:
    - ubuntu
  gather_facts: no

  vars:
    domains: 
      - example.com
      - facebook.com
      - twitter.com

  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes
      become: yes
      tags:
        - packages

    - name: Add php8.0 repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      become: yes
      tags:
        - packages 

    # apt-get install htop vim php8.0 kazam filezilla bluefish
    - name: Install cmatrix, vim, htop, mysql
      apt:
        name:
          - htop
          - vim
          - php8.0
          - kazam
          - filezilla
          - bluefish
        state: present
        update_cache: yes
      become: yes
      tags:
        - packages

  #   # - name: Copy static file
  #   #   copy:
  #   #     src: /tmp/test.txt
  #   #     dest: /tmp/out.txt

  # #   - name: Create file from template
  # #     template:
  # #       src: template.j2
  # #       dest: "/tmp/{{ item }}.txt"
  # #     loop: "{{ domains }}"
  # #     tags:
  # #       - template

  # # handlers:
  # #   - name: start mysql service
  # #     service: 
  # #       name: mysqld
  # #       state: started
  # #     become: yes